// ── Generador determinista del roster de árbitros (datos mock) ──────────────
//
// Genera los 770 árbitros de la petición del usuario con la distribución de
// `REFEREE_LEVEL_DISTRIBUTION`. Cada árbitro lleva un NICK ("nombre de guerra")
// ÚNICO, el nivel fino `refereeLevel` y la `category` legacy mapeada (para que
// el solver y la UI actuales no cambien).
//
// Nicks: cada uno es único por sí mismo, SIN sufijos numéricos ni romanos
// (nada de "ALTOS II") y de UNA SOLA palabra: sin espacios, sin "DE" y sin
// artículos ('FLACO', no 'EL FLACO'). El pool son ~1450 palabras sueltas
// curadas (topónimos madrileños + apodos castizos), deduplicadas y barajadas
// con el PRNG; árbitros consumen pool[0..769] y anotadores pool[770..1269].
//
// DETERMINISTA a propósito: usa un PRNG con semilla fija (mulberry32), sin
// `Math.random()` ni `Date.now()`. Así el server y el cliente producen el mismo
// roster (mock-data se importa desde componentes cliente) y no hay mismatch de
// hidratación en Next.

import {
  REFEREE_LEVELS,
  REFEREE_LEVEL_DISTRIBUTION,
  LEGACY_CATEGORY_BY_LEVEL,
  type RefereeLevel,
} from './referee-eligibility'

export type MockPerson = {
  id: string
  name: string
  email: string
  phone: string
  role: 'arbitro' | 'anotador'
  // Árbitros: provincial|autonomico|nacional|feb. Anotadores: escuela|autonomico|nacional.
  category: 'provincial' | 'autonomico' | 'nacional' | 'feb' | 'escuela'
  address: string
  postalCode: string
  municipalityId: string
  bankIban: string
  active: boolean
  hasCar: boolean
  authUserId: string | null
  createdAt: Date
  nick?: string
  refereeLevel?: RefereeLevel
}

// PRNG determinista (mulberry32).
function mulberry32(seed: number): () => number {
  let a = seed >>> 0
  return () => {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function shuffle<T>(arr: T[], rand: () => number): T[] {
  const a = arr.slice()
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    const tmp = a[i]
    a[i] = a[j]
    a[j] = tmp
  }
  return a
}

const NOMBRES = [
  'Alejandro',
  'Javier',
  'Daniel',
  'Carlos',
  'David',
  'Adrián',
  'Pablo',
  'Sergio',
  'Marcos',
  'Rubén',
  'Álvaro',
  'Iván',
  'Diego',
  'Jorge',
  'Raúl',
  'Miguel',
  'Ángel',
  'Fernando',
  'Óscar',
  'Guillermo',
  'Hugo',
  'Mario',
  'Víctor',
  'Antonio',
  'Andrés',
  'Laura',
  'Marta',
  'Sara',
  'Ana',
  'Cristina',
  'Lucía',
  'Paula',
  'Elena',
  'Nerea',
  'Beatriz',
  'Patricia',
  'Alba',
  'Carmen',
  'Irene',
  'Natalia',
  'Sofía',
  'Claudia',
  'Rocío',
  'Silvia',
  'Andrea',
  'Noelia',
  'Julia',
  'Marina',
  'Lorena',
  'Verónica',
]

const APELLIDOS = [
  'García',
  'Martínez',
  'López',
  'Sánchez',
  'González',
  'Rodríguez',
  'Fernández',
  'Pérez',
  'Gómez',
  'Ruiz',
  'Díaz',
  'Moreno',
  'Muñoz',
  'Álvarez',
  'Romero',
  'Alonso',
  'Gutiérrez',
  'Navarro',
  'Torres',
  'Domínguez',
  'Vázquez',
  'Ramos',
  'Gil',
  'Serrano',
  'Blanco',
  'Molina',
  'Morales',
  'Suárez',
  'Ortega',
  'Delgado',
  'Castro',
  'Ortiz',
  'Rubio',
  'Marín',
  'Sanz',
  'Núñez',
  'Iglesias',
  'Medina',
  'Garrido',
  'Cortés',
  'Castillo',
  'Santos',
  'Lozano',
  'Guerrero',
  'Cano',
  'Prieto',
  'Méndez',
  'Cruz',
  'Herrera',
  'Peña',
  'Flores',
  'Cabrera',
  'Campos',
  'Vega',
  'Fuentes',
  'Carmona',
]

const CALLES = [
  'Calle Mayor',
  'Calle de Alcalá',
  'Gran Vía',
  'Paseo de la Castellana',
  'Calle Bravo Murillo',
  'Calle de Atocha',
  'Calle de Toledo',
  'Avenida de América',
  'Calle de Fuencarral',
  'Calle de Serrano',
  'Paseo del Prado',
  'Calle de Goya',
  'Avenida de la Albufera',
  'Calle del Doctor Esquerdo',
  'Calle de Arturo Soria',
  'Avenida de los Poblados',
  'Calle de Embajadores',
  'Calle de Preciados',
  'Ronda de Valencia',
  'Calle de Segovia',
]

// Topónimos madrileños de UNA sola palabra (MAYÚSCULAS, solo letras, sin "DE"
// ni artículos; regex /^[A-ZÁÉÍÓÚÜÑ]+$/). El usuario: "ALTOS" (por su calle
// Altos de Cabrejas) y "CABREJAS". Organizado por bloques para mantenimiento;
// buildNickPool deduplica al final, pero evita repetir palabras entre bloques.
const LUGARES = [
  // Base histórica (barrios, municipios y parajes ya en uso)
  'ALTOS',
  'CABREJAS',
  'MALASAÑA',
  'VALLECAS',
  'CARABANCHEL',
  'LAVAPIÉS',
  'CHUECA',
  'LATINA',
  'USERA',
  'MORATALAZ',
  'CANILLEJAS',
  'HORTALEZA',
  'BARAJAS',
  'CHAMBERÍ',
  'RETIRO',
  'SALAMANCA',
  'ARGANZUELA',
  'TETUÁN',
  'ALUCHE',
  'VICÁLVARO',
  'VILLAVERDE',
  'PACÍFICO',
  'DELICIAS',
  'EMBAJADORES',
  'ATOCHA',
  'GOYA',
  'SOL',
  'CIBELES',
  'COLÓN',
  'BERNABÉU',
  'CALDERÓN',
  'MAGARIÑOS',
  'GETAFE',
  'ALCORCÓN',
  'MÓSTOLES',
  'LEGANÉS',
  'FUENLABRADA',
  'PARLA',
  'PINTO',
  'VALDEMORO',
  'ARANJUEZ',
  'COSLADA',
  'TORREJÓN',
  'RIVAS',
  'ARGANDA',
  'POZUELO',
  'MAJADAHONDA',
  'BOADILLA',
  'ALCOBENDAS',
  'GALAPAGAR',
  'TORRELODONES',
  'VILLALBA',
  'GUADARRAMA',
  'CERCEDILLA',
  'NAVACERRADA',
  'MANZANARES',
  'CHINCHÓN',
  'PATONES',
  'RASCAFRÍA',
  'ROBLEDO',
  'BUITRAGO',
  'TORRELAGUNA',
  'COLMENAR',
  'NAVALCARNERO',
  'HUMANES',
  'CIEMPOZUELOS',
  'ALGETE',
  'DAGANZO',
  'PARACUELLOS',
  'MECO',
  'LOECHES',
  'MORATA',
  'PERALES',
  'ESTREMERA',
  'VILLAREJO',
  'BELMONTE',
  'TIELMES',
  'CARABAÑA',
  'ORUSCO',
  'AMBITE',
  'PEZUELA',
  'SANTORCAZ',
  'ANCHUELO',
  'CORPA',
  'PIOZ',
  'PEDREZUELA',
  'GUADALIX',
  'MIRAFLORES',
  'BUSTARVIEJO',
  'VALDEMANCO',
  'GARGANTA',
  'CANENCIA',
  'LOZOYA',
  'PINILLA',
  'GASCONES',
  'BRAOJOS',
  'HORCAJO',
  'MADARCOS',
  'PRÁDENA',
  'ROBREGORDO',
  'SOMOSIERRA',
  'MONTEJO',
  'BERZOSA',
  'CERVERA',
  'REDUEÑA',
  'VENTURADA',
  'CABANILLAS',
  'TALAMANCA',
  'VALDEPIÉLAGOS',
  'RIBATEJADA',
  'FRESNO',
  'SERRANILLOS',
  'BATRES',
  'CUBAS',
  'CASARRUBUELOS',
  'MORALEJA',
  'ARROYOMOLINOS',
  'GRIÑÓN',
  'PARDO',
  'PEÑALARA',
  'JARAMA',
  'MADROÑO',
  'ALAMEDA',
  'ENCINA',
  'PRADERA',
  'BERRUECO',
  'MOLAR',
  'TALAMANCÓN',
  'VELILLA',
  'MEJORADA',
  // Municipios, pedanías y urbanizaciones de la CM (token distintivo)
  'ACEBEDA',
  'AJALVIR',
  'ALALPARDO',
  'ÁLAMO',
  'ALCALÁ',
  'ALDEA',
  'ALPEDRETE',
  'AOSLOS',
  'BAZTÁN',
  'BECERRIL',
  'BOALO',
  'BREA',
  'BRUNETE',
  'CABRERA',
  'CADALSO',
  'CALZADA',
  'CAMARMA',
  'CANTOS',
  'CENICIENTOS',
  'CHAPINERÍA',
  'CIUDALCAMPO',
  'COBEÑA',
  'COLLADO',
  'COLMENAREJO',
  'CUADRÓN',
  'ESCORIAL',
  'EUROVILLAS',
  'FRESNEDILLAS',
  'FUENTIDUEÑA',
  'GANDULLAS',
  'GARGANTILLA',
  'HIRUELA',
  'HORCAJUELO',
  'HOYO',
  'LOZOYUELA',
  'MANJIRÓN',
  'MATAELPINO',
  'MOLINOS',
  'MONTEPRÍNCIPE',
  'MORALZARZAL',
  'NAVALAFUENTE',
  'NAVALAGAMELLA',
  'NAVARREDONDA',
  'NAVAS',
  'OLMEDA',
  'OLMO',
  'OTERUELO',
  'PARDILLO',
  'PAREDES',
  'PELAYOS',
  'PEÑASCALES',
  'PERALEJO',
  'PIÑUÉCAR',
  'PUEBLA',
  'QUIJORNA',
  'ROBLEDILLO',
  'ROBLEDONDO',
  'ROZAS',
  'SANSE',
  'SERNA',
  'SERRACINES',
  'SERRADA',
  'SEVILLA',
  'SIETEIGLESIAS',
  'SOTO',
  'TITULCIA',
  'TORREMOCHA',
  'TORRES',
  'VALDARACETE',
  'VALDEAVERO',
  'VALDEIGLESIAS',
  'VALDELAGUNA',
  'VALDEMAQUEDA',
  'VALDEMORILLO',
  'VALDEOLMOS',
  'VALDETORRES',
  'VALDILECHA',
  'VALVERDE',
  'VEGA',
  'VELLÓN',
  'VILLACONEJOS',
  'VILLAMANRIQUE',
  'VILLAMANTA',
  'VILLAMANTILLA',
  'VILLANUEVA',
  'VILLAR',
  'VILLAVICIOSA',
  'VILLAVIEJA',
  'ZARZALEJO',
  // Barrios y distritos de Madrid capital
  'ABRANTES',
  'ACACIAS',
  'ADELFAS',
  'ÁGUILAS',
  'ALMAGRO',
  'ALMENARA',
  'ALMENDRALES',
  'ALVARADO',
  'AMBROZ',
  'AMPOSTA',
  'ARAPILES',
  'ARAVACA',
  'ARCOS',
  'ARGÜELLES',
  'AUSTRIAS',
  'AZCA',
  'BEGOÑA',
  'BERRUGUETE',
  'BUENAVISTA',
  'BUTARQUE',
  'CAMPAMENTO',
  'CANILLAS',
  'CASTELLANA',
  'CASTILLA',
  'CHAMARTÍN',
  'CHOPERA',
  'COMILLAS',
  'CONCEPCIÓN',
  'CORRALEJOS',
  'COSTILLARES',
  'ENTREVÍAS',
  'ESTRELLA',
  'FONTARRÓN',
  'FUENCARRAL',
  'FUENTELARREINA',
  'GAZTAMBIDE',
  'GUINDALERA',
  'HELLÍN',
  'HISPANOAMÉRICA',
  'IBIZA',
  'IMPERIAL',
  'JERÓNIMOS',
  'JUSTICIA',
  'LEGAZPI',
  'LETRAS',
  'LISTA',
  'LUCERO',
  'MANOTERAS',
  'MARAVILLAS',
  'MARROQUINA',
  'MINGORRUBIO',
  'MIRASIERRA',
  'MONCLOA',
  'MONTECARMELO',
  'MOSCARDÓ',
  'NUMANCIA',
  'OPAÑEL',
  'ORCASITAS',
  'ORCASUR',
  'PALACIO',
  'PALOMERAS',
  'PALOS',
  'PAVONES',
  'PEÑAGRANDE',
  'PEÑUELAS',
  'PILAR',
  'PINAR',
  'PLANTÍO',
  'PORTAZGO',
  'PRADOLONGO',
  'PROSPERIDAD',
  'QUINTANA',
  'RECOLETOS',
  'REJAS',
  'ROSALES',
  'ROSAS',
  'SANCHINARRO',
  'SIMANCAS',
  'SUANZES',
  'TIMÓN',
  'TRAFALGAR',
  'UNIVERSIDAD',
  'VALDEACEDERAS',
  'VALDEBEBAS',
  'VALDEBERNARDO',
  'VALDEFUENTES',
  'VALDELATAS',
  'VALDEMARÍN',
  'VALDERRIBAS',
  'VALDEZARZA',
  'VALLEHERMOSO',
  'VENTAS',
  'VENTILLA',
  'VINATEROS',
  'ZOFÍO',
  // Hitos, fuentes, estaciones y metro castizo
  'ALCACHOFA',
  'ALSACIA',
  'APOLO',
  'ASCAO',
  'BATÁN',
  'CARMEN',
  'CARTAGENA',
  'CUZCO',
  'DEBOD',
  'EMPALME',
  'ESTRECHO',
  'FARO',
  'IGLESIA',
  'LAGO',
  'MATADERO',
  'METROPOLITANO',
  'MINERVA',
  'NEPTUNO',
  'OPORTO',
  'ORENSE',
  'PIRÁMIDES',
  'PIRULÍ',
  'PLANETARIO',
  'TABACALERA',
  'URGEL',
  // Sierra: cumbres, puertos y collados
  'ABANTOS',
  'ALMODÓVAR',
  'ATALAYA',
  'BOLA',
  'COTOS',
  'FUENFRÍA',
  'GARABITAS',
  'GUARRAMILLAS',
  'LEONES',
  'MALICIOSA',
  'MARAÑOSA',
  'MONDALINDO',
  'MORCUERA',
  'NAJARRA',
  'NAVAFRÍA',
  'NEVERO',
  'PEÑOTA',
  'PINGARRÓN',
  'TELÉGRAFO',
  'VALDEMARTÍN',
  'YELMO',
  // Ríos, arroyos y embalses
  'ABROÑIGAL',
  'ALBERCHE',
  'ATAZAR',
  'AULENCIA',
  'CANALILLO',
  'COFIO',
  'CULEBRO',
  'GASCO',
  'HENARES',
  'MEAQUES',
  'NAVALMEDIO',
  'PICADAS',
  'PRADILLO',
  'RIOSEQUILLO',
  'SANTILLANA',
  'TAJO',
  'TAJUÑA',
  'TOROTE',
  'VALMAYOR',
  // Parajes, dehesas, montes y cañadas
  'ALDEHUELA',
  'ALISEDA',
  'BERROCAL',
  'BOYAL',
  'CAMORRITOS',
  'CAMPILLO',
  'CANCHAL',
  'CANTUEÑA',
  'CAPRICHO',
  'CARRASCAL',
  'CASTAÑAR',
  'CHAPARRAL',
  'CORDEL',
  'DEHESA',
  'ENCINAR',
  'ESPARTAL',
  'FRESNEDA',
  'GALIANA',
  'HERRERÍA',
  'JARAL',
  'LAGUNA',
  'MADROÑAL',
  'MAJADA',
  'MERINAS',
  'MONCALVILLO',
  'NAVA',
  'NAVALVILLAR',
  'PEDRIZA',
  'POLVORANCA',
  'PORCAL',
  'QUEJIGAL',
  'REGAJAL',
  'RETAMAR',
  'ROBLEDAL',
  'ROSALEDA',
  'SEGOVIANA',
  'SILLA',
  'SOLANA',
  'SOTILLO',
  'TABLADA',
  'TOMILLAR',
  'TORREÓN',
  'UMBRÍA',
  'VALDECARROS',
  'VALDELAMASA',
  'VENTORRILLO',
  'VEREDA',
  'VIVEROS',
  'ZARZAL',
  // Calles, plazas y puertas castizas
  'ACUERDO',
  'ALCÁNTARA',
  'ALMIRANTE',
  'ALMUDENA',
  'AMANIEL',
  'APODACA',
  'ARENAL',
  'ARGUMOSA',
  'AYALA',
  'BAILÉN',
  'BALLESTA',
  'BARCELÓ',
  'BARQUILLO',
  'BELÉN',
  'BILBAO',
  'BOTONERAS',
  'CABESTREROS',
  'CALLAO',
  'CANTARRANAS',
  'CARRANZA',
  'CARRETAS',
  'CASCORRO',
  'CAVA',
  'CEBADA',
  'CEDACEROS',
  'CERVANTES',
  'CLAVEL',
  'CODO',
  'CORREDERA',
  'COVARRUBIAS',
  'CUCHILLEROS',
  'CURTIDORES',
  'DAOÍZ',
  'DESCALZAS',
  'DESENGAÑO',
  'ECHEGARAY',
  'ESPARTEROS',
  'ESPEJO',
  'FERRAZ',
  'FLORIDA',
  'FORTUNY',
  'FÚCAR',
  'GALILEO',
  'GALDÓS',
  'GÓNGORA',
  'GRAVINA',
  'GUADALAJARA',
  'HERRADORES',
  'HERMOSILLA',
  'HIERRO',
  'HILERAS',
  'HUERTAS',
  'HUMILLADERO',
  'INFANTAS',
  'LAGASCA',
  'LARRA',
  'LATONEROS',
  'LEGANITOS',
  'LIBERTAD',
  'LOPE',
  'LUNA',
  'MAGDALENA',
  'MALDONADO',
  'MAYOR',
  'MELANCÓLICOS',
  'MONTELEÓN',
  'MONTERA',
  'MONTESA',
  'MORATÍN',
  'MORERÍA',
  'MOROS',
  'MOSTENSES',
  'MURILLO',
  'NARVÁEZ',
  'NOVICIADO',
  'NUNCIO',
  'OLAVIDE',
  'OLIVAR',
  'ÓPERA',
  'ORIENTE',
  'PADILLA',
  'PAJA',
  'PELAYO',
  'PELIGROS',
  'PEZ',
  'PIAMONTE',
  'PONTEJOS',
  'PONTONES',
  'POSTAS',
  'PRADO',
  'PRECIADOS',
  'PRIM',
  'PRINCESA',
  'QUEVEDO',
  'QUIÑONES',
  'RASTRO',
  'REDONDILLA',
  'RIBERA',
  'SACRAMENTO',
  'SALESAS',
  'SALITRE',
  'SEGOVIA',
  'SERRANO',
  'SOMBRERETE',
  'TABERNILLAS',
  'TIRSO',
  'TOLEDO',
  'TRIBULETE',
  'TRIBUNAL',
  'VALENCIA',
  'VELARDE',
  'VELÁZQUEZ',
  'VENTURA',
  'VERGARA',
  'VICTORIA',
  'VISTILLAS',
  'ZURBANO',
  'ZURBARÁN',
  // Nombres históricos y legendarios de Madrid
  'CARPETANO',
  'MANTUA',
  'MATRICE',
  'MAYRIT',
  'URSARIA',
]

// Apodos castizos de UNA sola palabra (MAYÚSCULAS, solo letras, sin artículos:
// 'FLACO', no 'EL FLACO'). Mismas reglas y organización por bloques que
// LUGARES. OJO: estas 9 palabras están RESERVADAS para los nicks demo de
// mock-data y NO deben entrar en el pool: DECANO, JEFA, CATEDRÁTICO, CONDESA,
// CRONISTA, COMENDADOR, VIRTUOSA, SIBILA, ESCRIBANO.
const APODOS = [
  // Base histórica (normalizada sin artículo)
  'FLACO',
  'RUBIO',
  'LARGO',
  'CHATO',
  'ZURDO',
  'GRECO',
  'CID',
  'TARZÁN',
  'MAGIC',
  'PISTOLERO',
  'FRANCOTIRADOR',
  'CANASTERO',
  'REBOTE',
  'TAPÓN',
  'SILBATO',
  'BOCINA',
  'RELÁMPAGO',
  'TRUENO',
  'HURACÁN',
  'CICLÓN',
  'RAYO',
  'CÓNDOR',
  'HALCÓN',
  'ÁGUILA',
  'LINCE',
  'PUMA',
  'LOBO',
  'ZORRO',
  'TORO',
  'BISONTE',
  'PANTERA',
  'GACELA',
  'GUEPARDO',
  'MAMBA',
  'COBRA',
  'TIGRE',
  'CANELA',
  'PIMIENTA',
  'AZAFRÁN',
  'PEREJIL',
  'LAUREL',
  'TOMILLO',
  'ORÉGANO',
  'HINOJO',
  'CASTIZO',
  'CHULAPO',
  'GATO',
  'OSO',
  'ROSCÓN',
  'CHOTIS',
  'VERBENA',
  'FAROLA',
  'ISIDRO',
  'PALOMA',
  'MELÓN',
  'GARBANZO',
  'ANÍS',
  'ROMERO',
  'CHAPU',
  'MOTA',
  'DÍMAS',
  'MOSQUITO',
  'CHICHARRO',
  'PROFE',
  'SHERIFF',
  'MÍSTER',
  'GENERAL',
  'CAPITÁN',
  'MAESTRO',
  'DOCTOR',
  // Oficios tradicionales y castizos
  'ACOMODADOR',
  'AFILADOR',
  'AGUADOR',
  'ALCALDE',
  'ALFARERO',
  'ALGUACIL',
  'ALQUIMISTA',
  'AMANUENSE',
  'APUNTADOR',
  'ARCHIVERO',
  'ARRIERO',
  'ASTRÓNOMO',
  'BARBERO',
  'BARQUILLERO',
  'BARRENDERO',
  'BATANERO',
  'BESUGUERO',
  'BETUNERO',
  'BODEGUERO',
  'BOTÁNICO',
  'BOTICARIO',
  'BOTIJERO',
  'BOTONES',
  'BUHONERO',
  'BUÑOLERO',
  'CABRERO',
  'CACHARRERO',
  'CAJISTA',
  'CALDERERO',
  'CALESERO',
  'CAMPANERO',
  'CANTAOR',
  'CANTERO',
  'CARBONERO',
  'CARRETERO',
  'CARTERO',
  'CASTAÑERA',
  'CERERO',
  'CERILLERO',
  'CERRAJERO',
  'CETRERO',
  'CHATARRERO',
  'CHISPERO',
  'CHURRERO',
  'CIGARRERA',
  'COBRADOR',
  'COCHERO',
  'COLCHONERO',
  'COLMENERO',
  'CONFITERO',
  'COPLERO',
  'COSTURERA',
  'CRISTALERO',
  'CURANDERO',
  'DOMADOR',
  'DROGUERO',
  'EMPEDRADOR',
  'ENCAJERA',
  'ESPARTERO',
  'ESQUILADOR',
  'ESTANQUERO',
  'FAROLERO',
  'FERIANTE',
  'FERROVIARIO',
  'FLORISTA',
  'FOGONERO',
  'FONDISTA',
  'FONTANERO',
  'FRUTERO',
  'GABARRERO',
  'GACETILLERO',
  'GAITERO',
  'GALLINERO',
  'GAÑÁN',
  'GUARDAGUJAS',
  'HERRADOR',
  'HERRERO',
  'HORNERO',
  'HORTELANO',
  'JABONERO',
  'JUGLAR',
  'LAVANDERA',
  'LECHERO',
  'LEÑADOR',
  'LIBRERO',
  'LIMPIABOTAS',
  'MAGO',
  'MALABARISTA',
  'MAQUINISTA',
  'MAYORAL',
  'MELONERO',
  'MESONERO',
  'MOLINERO',
  'MONAGUILLO',
  'MONTERO',
  'OJEADOR',
  'ORGANILLERO',
  'ORGANISTA',
  'PAJARERO',
  'PALMERO',
  'PALOMERO',
  'PANADERO',
  'PASTOR',
  'PESCADERO',
  'PIÑONERO',
  'PLATERO',
  'POCERO',
  'POSADERO',
  'PREGONERO',
  'QUESERO',
  'QUINCALLERO',
  'RAMILLETERA',
  'RECADERO',
  'REGIDOR',
  'RELOJERO',
  'RESINERO',
  'REVISOR',
  'SACRISTÁN',
  'SASTRE',
  'SEGADOR',
  'SERENO',
  'SOMBRERERO',
  'TABERNERO',
  'TAHONERO',
  'TALABARTERO',
  'TAQUILLERO',
  'TEJEDOR',
  'TEJERO',
  'TENDERO',
  'TITIRITERO',
  'TOCAOR',
  'TRAMOYISTA',
  'TRANVIARIO',
  'TRAPERO',
  'TRAPECISTA',
  'TROVADOR',
  'VAQUERO',
  'VELERO',
  'VENTERO',
  'VIDRIERO',
  'VIGÍA',
  'YESERO',
  'YUNTERO',
  'ZAGAL',
  'ZAPATERO',
  // Rasgos, motes y tipos castizos
  'AGUDO',
  'APAÑADO',
  'ATREVIDO',
  'AVISPADO',
  'AZOGUE',
  'AZOTACALLES',
  'BACHILLER',
  'BARBAS',
  'BIGOTES',
  'BISOÑO',
  'BÓLIDO',
  'BOHEMIO',
  'BOTARATE',
  'BRAVÍO',
  'BRAVO',
  'BRIBÓN',
  'BROMISTA',
  'CABAL',
  'CACHAS',
  'CALAVERA',
  'CALVO',
  'CAMELISTA',
  'CANIJO',
  'CANOSO',
  'CARADURA',
  'CASTIGADOR',
  'CEJIJUNTO',
  'CENTELLA',
  'CHARLATÁN',
  'CHINCHE',
  'CHISPA',
  'CHULAPA',
  'CHULETA',
  'COLORADO',
  'COMILÓN',
  'CORREVEIDILE',
  'COTILLA',
  'CUENTISTA',
  'CUMPLIDOR',
  'CURTIDO',
  'DESCARADO',
  'DORMILÓN',
  'ENJUTO',
  'ESPABILADO',
  'ESPIGADO',
  'FANTASMA',
  'FANTOCHE',
  'FARDÓN',
  'FENÓMENO',
  'FIERA',
  'FIGURA',
  'FILÓSOFO',
  'FINOLIS',
  'FLAMENCO',
  'FORMAL',
  'FORNIDO',
  'FORZUDO',
  'FRESCALES',
  'FRESCO',
  'FUGAZ',
  'GAFOTAS',
  'GALÁN',
  'GALLITO',
  'GAMBERRO',
  'GANSO',
  'GENIO',
  'GIGANTE',
  'GOLFO',
  'GOLOSO',
  'GOYESCA',
  'GRACIOSO',
  'GRANDULLÓN',
  'GRANUJA',
  'GUAPO',
  'GUASÓN',
  'JAQUE',
  'JETA',
  'LANZADO',
  'LECHUGUINO',
  'LETRADO',
  'LIANTE',
  'LICENCIADO',
  'LIGERO',
  'LISTILLO',
  'LUNARES',
  'MADRUGADOR',
  'MAJA',
  'MAJO',
  'MANAZAS',
  'MANITAS',
  'MANOLA',
  'MAÑOSO',
  'MELENAS',
  'MEMBRUDO',
  'METEORO',
  'METOMENTODO',
  'MOFLETES',
  'MORENO',
  'NARIZOTAS',
  'NOCTÁMBULO',
  'NOVATO',
  'OCURRENTE',
  'OREJÓN',
  'OSADO',
  'PANOLI',
  'PARLANCHÍN',
  'PATILARGO',
  'PATILLAS',
  'PECAS',
  'PELIRROJO',
  'PEQUE',
  'PERIPUESTO',
  'PETIMETRE',
  'PÍCARO',
  'PILLO',
  'PINTURERO',
  'PISAVERDE',
  'POETA',
  'POLVORILLA',
  'PRIMAVERA',
  'RAUDO',
  'REDICHO',
  'RENACUAJO',
  'REPIPI',
  'RESALADO',
  'RISUEÑO',
  'RIZOS',
  'RONCO',
  'RUBIALES',
  'SABIHONDO',
  'SALADO',
  'SEÑORITO',
  'SECO',
  'SOCARRÓN',
  'SOÑADOR',
  'TARAMBANA',
  'TEMPLADO',
  'TENORIO',
  'TIERNO',
  'TORBELLINO',
  'TRAGALDABAS',
  'TRAGÓN',
  'TRASNOCHADOR',
  'TRUHÁN',
  'TUNANTE',
  'VALENTÓN',
  'VALIENTE',
  'VELOZ',
  'VERBENERO',
  'VETERANO',
  'VIVALES',
  'VIVIDOR',
  'ZALAMERO',
  'ZAMPABOLLOS',
  'ZAMPÓN',
  'ZANCUDO',
  'ZANQUILARGO',
  'ZASCANDIL',
  // Taurino e hípico
  'ALAZÁN',
  'ALBAHÍO',
  'AMAZONA',
  'ASTADO',
  'BANDERILLA',
  'BANDERILLERO',
  'BERRENDO',
  'BOMBITA',
  'BUREL',
  'CAMPEADOR',
  'CAPOTE',
  'CÁRDENO',
  'CENTAURO',
  'CHICUELINA',
  'CORCEL',
  'CORDOBÉS',
  'CÚCHARES',
  'DIESTRO',
  'ESPADA',
  'ESPUELA',
  'ESTRIBO',
  'FAROL',
  'FRASCUELO',
  'GALOPE',
  'GANADERO',
  'GAONERA',
  'JACA',
  'JINETE',
  'LAGARTIJO',
  'MALETILLA',
  'MATADOR',
  'MIURA',
  'MORLACO',
  'NOVILLERO',
  'PALOMO',
  'PAQUIRO',
  'PICADOR',
  'POTRO',
  'REBOLERA',
  'REJÓN',
  'RETINTO',
  'TORDO',
  'TORERO',
  'TRINCHERA',
  'TROTÓN',
  'VERÓNICA',
  'VICTORINO',
  'ZAINO',
  // Milicia, mar y esgrima
  'ALABARDERO',
  'ALFÉREZ',
  'ARQUERO',
  'ARTILLERO',
  'BALLESTERO',
  'BRIGADIER',
  'BUCANERO',
  'CADETE',
  'CALATRAVA',
  'CENTINELA',
  'CORACERO',
  'CORNETA',
  'CORONEL',
  'CORSARIO',
  'DRAGÓN',
  'ESPADACHÍN',
  'ESPARTANO',
  'FILIBUSTERO',
  'FLORETE',
  'GAVIERO',
  'GLADIADOR',
  'GRANADERO',
  'GRUMETE',
  'GUARDIÁN',
  'HONDERO',
  'HÚSAR',
  'LANCERO',
  'LUCHADOR',
  'MARISCAL',
  'MOSQUETERO',
  'PATRÓN',
  'PELOTÓN',
  'PIQUERO',
  'PIRATA',
  'PÚGIL',
  'QUINTO',
  'SABLISTA',
  'SAMURÁI',
  'SARGENTO',
  'TAMBOR',
  'TERCIO',
  'TIMONEL',
  'TROMPETA',
  'VIKINGO',
  'ZAPADOR',
  // Deportivo (baloncesto, fútbol, ciclismo, pelota...)
  'ALERO',
  'ARIETE',
  'ARO',
  'BANDEJA',
  'CANCERBERO',
  'CANTERANO',
  'CAÑO',
  'CAÑONERO',
  'CARRILERO',
  'CESTA',
  'CHILENA',
  'CHISTERA',
  'CHUPÓN',
  'CRONO',
  'CRONÓMETRO',
  'DISCÓBOLO',
  'DOBLE',
  'ESCALADOR',
  'ESCOLTA',
  'ESCORPIÓN',
  'ESTRATEGA',
  'FAROLILLO',
  'FINTA',
  'FRONTÓN',
  'GANCHO',
  'GIMNASTA',
  'GOLEADOR',
  'GREGARIO',
  'GUARDAMETA',
  'JABALINA',
  'LANZADOR',
  'LÍBERO',
  'MARTILLO',
  'MATE',
  'MEDIAPUNTA',
  'PACHANGA',
  'PALMEO',
  'PALOMITA',
  'PELOTARI',
  'PICHICHI',
  'PÍVOT',
  'PIZARRA',
  'PORTERO',
  'RABONA',
  'RACHA',
  'REGATE',
  'REGATISTA',
  'REMERO',
  'RODADOR',
  'ROSCA',
  'RULETA',
  'SALTADOR',
  'SOMBRERO',
  'TABLERO',
  'TACÓN',
  'TIJERA',
  'TRIPLE',
  'TRIPLISTA',
  'VALLISTA',
  'VASELINA',
  'VELOCISTA',
  'VOLEA',
  'ZAGUERO',
  'ZAMORA',
  // Fauna madrileña y castiza
  'ABEJARUCO',
  'ABEJORRO',
  'ABUBILLA',
  'AGUILUCHO',
  'ALCARAVÁN',
  'ALCAUDÓN',
  'ALCOTÁN',
  'ALIMOCHE',
  'ALONDRA',
  'ANGUILA',
  'ARDILLA',
  'ARMIÑO',
  'AVEFRÍA',
  'AVIÓN',
  'AVISPA',
  'AVUTARDA',
  'AZOR',
  'AZULÓN',
  'BARBO',
  'BICHO',
  'BOGA',
  'BÚHO',
  'BUITRE',
  'CACHALOTE',
  'CALANDRIA',
  'CAMARÓN',
  'CANGREJO',
  'CÁRABO',
  'CARNERO',
  'CARPA',
  'CARRACA',
  'CASTOR',
  'CERNÍCALO',
  'CHICHARRA',
  'CHORLITO',
  'CHOVA',
  'CIERVO',
  'CIGARRA',
  'CIGÜEÑA',
  'CODORNIZ',
  'COMADREJA',
  'CORMORÁN',
  'CORNEJA',
  'CORZO',
  'COTORRA',
  'CUCO',
  'CUERVO',
  'CULEBRA',
  'CURRUCA',
  'DELFÍN',
  'ERIZO',
  'ESCARABAJO',
  'ESTORNINO',
  'FAISÁN',
  'GALÁPAGO',
  'GALLIPATO',
  'GALLO',
  'GAMO',
  'GARDUÑA',
  'GARZA',
  'GAVILÁN',
  'GAVIOTA',
  'GAZAPO',
  'GINETA',
  'GOBIO',
  'GOLONDRINA',
  'GORRIÓN',
  'GRAJO',
  'GRILLO',
  'HERRERILLO',
  'HORMIGA',
  'JABALÍ',
  'JILGUERO',
  'LAGARTIJA',
  'LAGARTO',
  'LECHUZA',
  'LIBÉLULA',
  'LIEBRE',
  'LIRÓN',
  'LUCIÉRNAGA',
  'LUCIO',
  'MARIPOSA',
  'MARTINETE',
  'MELONCILLO',
  'MILANO',
  'MIRLO',
  'MOCHUELO',
  'MUFLÓN',
  'MURCIÉLAGO',
  'MUSARAÑA',
  'NUTRIA',
  'OROPÉNDOLA',
  'PERDIGÓN',
  'PERDIZ',
  'PETIRROJO',
  'PICAPINOS',
  'PINZÓN',
  'PIRAÑA',
  'QUEBRANTAHUESOS',
  'RANA',
  'RATÓN',
  'RATONERO',
  'REYEZUELO',
  'RUISEÑOR',
  'SALAMANDRA',
  'SALTAMONTES',
  'SISÓN',
  'SOMORMUJO',
  'TÁBANO',
  'TARABILLA',
  'TEJÓN',
  'TIBURÓN',
  'TOPO',
  'TÓRTOLA',
  'TORTUGA',
  'TRUCHA',
  'TURÓN',
  'URRACA',
  'VENADO',
  'VENCEJO',
  'VERDERÓN',
  'VERRACO',
  'ZAMPULLÍN',
  'ZÁNGANO',
  'ZORZAL',
  // Flora y monte
  'ABROJO',
  'ACEBO',
  'AJEDREA',
  'ALCORNOQUE',
  'ALHELÍ',
  'ALMENDRO',
  'AMAPOLA',
  'ARCE',
  'AVELLANO',
  'AZUCENA',
  'BELLOTA',
  'BREVA',
  'BREZO',
  'CAMPANILLA',
  'CANTUESO',
  'CARDO',
  'CARRASCA',
  'CARRIZO',
  'CEREZO',
  'CIRUELO',
  'CLAVELLINA',
  'CHOPO',
  'ENDRINA',
  'ENEBRO',
  'ESCARAMUJO',
  'ESPARTO',
  'ESPINO',
  'ESPLIEGO',
  'ESTEPA',
  'GAYUBA',
  'GERANIO',
  'HELECHO',
  'HIEDRA',
  'HIGUERA',
  'JARA',
  'JAZMÍN',
  'JUNCO',
  'MADRESELVA',
  'MAJUELO',
  'MALVA',
  'MANZANO',
  'MEJORANA',
  'MIMBRE',
  'MORA',
  'MORAL',
  'NARDO',
  'NUEZ',
  'OLIVO',
  'ORTIGA',
  'PARRA',
  'PERAL',
  'PINO',
  'PIORNO',
  'PIÑA',
  'REBOLLO',
  'RETAMA',
  'ROBLE',
  'RUDA',
  'SABINA',
  'SALVIA',
  'SAUCE',
  'SERBAL',
  'TEJO',
  'VIOLETA',
  'ZARZA',
  'ZARZAMORA',
  // Cielo y clima
  'ÁBREGO',
  'AGUACERO',
  'ALBORADA',
  'BOCHORNO',
  'BORRASCA',
  'CALIMA',
  'CENIT',
  'CHUBASCO',
  'CIERZO',
  'COMETA',
  'ESCARCHA',
  'GALERNA',
  'GRANIZO',
  'LEVANTE',
  'MATACABRAS',
  'MONZÓN',
  'NIEBLA',
  'PONIENTE',
  'RELENTE',
  'REMOLINO',
  'SIROCO',
  'SOLANO',
  'TIFÓN',
  'TORMENTA',
  'TRAMONTANA',
  'TROMBA',
  'VENDAVAL',
  'VENTISCA',
  'VENTOLERA',
  // Gastronomía castiza
  'ADOBO',
  'ALTRAMUZ',
  'BACALAO',
  'BARTOLILLO',
  'BESUGO',
  'BOQUERÓN',
  'BOTIJO',
  'BOTÍN',
  'BRAVAS',
  'BUÑUELO',
  'CALAMAR',
  'CALLOS',
  'CAÑA',
  'CARACOL',
  'CARAMELO',
  'CASTAÑA',
  'CAZALLA',
  'CHICHARRÓN',
  'CHOCOLATE',
  'CHURRO',
  'CLARETE',
  'COCIDO',
  'CROQUETA',
  'ENTRESIJOS',
  'ESCABECHE',
  'GACHAS',
  'GALLINEJAS',
  'GASEOSA',
  'HORCHATA',
  'LIMONADA',
  'MELINDRE',
  'MEMBRILLO',
  'MIGAS',
  'MORCILLA',
  'MOSTO',
  'PELADILLA',
  'PESTIÑO',
  'PICATOSTE',
  'PINCHO',
  'PISTO',
  'PORRA',
  'PORRÓN',
  'POTAJE',
  'PUCHERO',
  'REGALIZ',
  'ROSQUILLA',
  'SIFÓN',
  'TORREZNO',
  'TORRIJA',
  'TORTILLA',
  'VALDEPEÑAS',
  'VERMÚ',
  'YEMA',
  // Música, juego y fiesta
  'ALMIREZ',
  'BANDURRIA',
  'BOLICHE',
  'BRINDIS',
  'BRISCA',
  'BULERÍA',
  'BULLA',
  'BUSCAPIÉS',
  'CABEZUDO',
  'CANICA',
  'CANTE',
  'CASTAÑUELA',
  'CHARANGA',
  'CHASCARRILLO',
  'CHINCHÍN',
  'CHUPINAZO',
  'CINQUILLO',
  'COHETE',
  'COMBA',
  'COMPÁS',
  'CONFETI',
  'COPLA',
  'COTILLÓN',
  'CUPLÉ',
  'DIANA',
  'DOMINÓ',
  'DONAIRE',
  'DUENDE',
  'ENTREMÉS',
  'ESCONDITE',
  'ESTRIBILLO',
  'FANDANGO',
  'FARRA',
  'FARRUCA',
  'GARBO',
  'GUÁ',
  'GUATEQUE',
  'GUIÑOL',
  'JALEO',
  'JARANA',
  'JOTA',
  'JUERGA',
  'JULEPE',
  'LAÚD',
  'MATASUEGRAS',
  'MECHA',
  'MELOPEA',
  'MUS',
  'NORIA',
  'OCA',
  'ORGANILLO',
  'PANDERETA',
  'PARCHÍS',
  'PARRANDA',
  'PASACALLES',
  'PASODOBLE',
  'PELELE',
  'PEONZA',
  'PETANCA',
  'PETARDO',
  'PIROPO',
  'POSTÍN',
  'RAYUELA',
  'REQUIEBRO',
  'RONDA',
  'RONDALLA',
  'RUMBO',
  'SAINETE',
  'SALERO',
  'SEGUIDILLA',
  'SERPENTINA',
  'SOLEÁ',
  'SOLFA',
  'TABA',
  'TABLAO',
  'TAJADA',
  'TIOVIVO',
  'TÓMBOLA',
  'TONADILLA',
  'TRACA',
  'TROMPA',
  'TROMPO',
  'TUNO',
  'TUTE',
  'ZAMBOMBA',
  'ZAPATEADO',
  'ZARZUELA',
  // Mitología y leyenda
  'ATLANTE',
  'BABIECA',
  'BUSCÓN',
  'CÍCLOPE',
  'CLARÍN',
  'CLAVILEÑO',
  'COLADA',
  'COLOSO',
  'ESFINGE',
  'FÉNIX',
  'FÍGARO',
  'GOLIAT',
  'GRIFO',
  'HÉRCULES',
  'LAZARILLO',
  'MERCURIO',
  'MINOTAURO',
  'PEGASO',
  'QUIJOTE',
  'QUIMERA',
  'ROCINANTE',
  'SALOMÓN',
  'SANSÓN',
  'SIRENA',
  'TITÁN',
  'TIZONA',
  'TRITÓN',
  'ULISES',
  'VULCANO',
]

function slug(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '.')
    .replace(/(^\.|\.$)/g, '')
}

// Pool de nicks únicos: SOLO palabras sueltas (una palabra, MAYÚSCULAS, solo
// letras), barajadas de forma determinista y deduplicadas con Set. Debe tener
// ≥1300 entradas únicas (se consumen 1270: 770 árbitros + 500 anotadores).
// Exportada para que los tests validen tamaño y restricciones del pool.
export function buildNickPool(rand: () => number): string[] {
  const seen = new Set<string>()
  const pool: string[] = []
  for (const nick of shuffle([...LUGARES, ...APODOS], rand)) {
    if (!seen.has(nick)) {
      seen.add(nick)
      pool.push(nick)
    }
  }
  return pool
}

/**
 * Genera el roster de 770 árbitros. `municipalities` debe traer id y nombre
 * (se pasa por parámetro para evitar un ciclo de imports con mock-data).
 */
export function generateReferees(municipalities: { id: string; name: string }[]): MockPerson[] {
  const rand = mulberry32(0x5eed_a17b) // semilla fija → roster reproducible
  const madrid = municipalities.find((m) => m.name === 'Madrid') ?? municipalities[0]
  const others = municipalities.filter((m) => m.id !== madrid.id)
  const nickPool = buildNickPool(rand)

  const people: MockPerson[] = []
  let n = 0

  for (const level of REFEREE_LEVELS) {
    const count = REFEREE_LEVEL_DISTRIBUTION[level]
    for (let i = 0; i < count; i++) {
      const seq = String(n + 1).padStart(4, '0')
      const nombre = NOMBRES[Math.floor(rand() * NOMBRES.length)]
      const ap1 = APELLIDOS[Math.floor(rand() * APELLIDOS.length)]
      const ap2 = APELLIDOS[Math.floor(rand() * APELLIDOS.length)]
      const name = `${nombre} ${ap1} ${ap2}`

      // Sesgo a Madrid capital (~45%); resto reparte por los demás municipios.
      const muni = rand() < 0.45 ? madrid : others[Math.floor(rand() * others.length)]

      const calle = CALLES[Math.floor(rand() * CALLES.length)]
      const num = 1 + Math.floor(rand() * 120)
      const cp = `28${String(1 + Math.floor(rand() * 999)).padStart(3, '0')}`
      const phone = `6${String(10_000_000 + Math.floor(rand() * 89_999_999))}`
      const ibanBody = Array.from({ length: 22 }, () => Math.floor(rand() * 10)).join('')

      people.push({
        id: `person-a${seq}`,
        name,
        email: `${slug(nombre)}.${slug(ap1)}${seq}@fbm-arbitros.example`,
        phone,
        role: 'arbitro',
        category: LEGACY_CATEGORY_BY_LEVEL[level],
        address: `${calle} ${num}, ${cp} ${muni.name}`,
        postalCode: cp,
        municipalityId: muni.id,
        bankIban: `ES${ibanBody}`,
        active: true,
        hasCar: rand() < 0.85, // la mayoría con coche (regla del solver)
        authUserId: null,
        createdAt: new Date('2025-09-01'),
        nick: nickPool[n],
        refereeLevel: level,
      })
      n++
    }
  }

  return people
}

// ── Roster de anotadores (oficiales de mesa) ────────────────────────────────
//
// Los anotadores tienen su propia escala de categorías: escuela < autonómica <
// nacional (independiente de la de árbitros). Distribución piramidal (500, ≥ el
// mínimo pedido por el usuario). Los nicks salen del MISMO pool que los árbitros
// pero desplazados por REFEREE_TOTAL, así ningún anotador comparte nick con un
// árbitro y todo el roster queda con nick único.

type ScorerCategory = 'escuela' | 'autonomico' | 'nacional'

const SCORER_CATEGORY_DISTRIBUTION: { category: ScorerCategory; count: number }[] = [
  { category: 'nacional', count: 90 },
  { category: 'autonomico', count: 160 },
  { category: 'escuela', count: 250 },
] // total = 500

const REFEREE_TOTAL = Object.values(REFEREE_LEVEL_DISTRIBUTION).reduce((a, b) => a + b, 0)

/**
 * Genera el roster de anotadores. Mismo estilo determinista que
 * `generateReferees`; nicks únicos respecto a los árbitros (offset del pool).
 */
export function generateScorers(municipalities: { id: string; name: string }[]): MockPerson[] {
  // Pool con la MISMA semilla que los árbitros → idéntico orden; el offset
  // REFEREE_TOTAL garantiza que ningún anotador comparte nick con un árbitro.
  const nickPool = buildNickPool(mulberry32(0x5eed_a17b))
  const rand = mulberry32(0x5c04_e5b1) // semilla propia → atributos variados

  const madrid = municipalities.find((m) => m.name === 'Madrid') ?? municipalities[0]
  const others = municipalities.filter((m) => m.id !== madrid.id)

  const people: MockPerson[] = []
  let n = 0

  for (const { category, count } of SCORER_CATEGORY_DISTRIBUTION) {
    for (let i = 0; i < count; i++) {
      const seq = String(n + 1).padStart(4, '0')
      const nombre = NOMBRES[Math.floor(rand() * NOMBRES.length)]
      const ap1 = APELLIDOS[Math.floor(rand() * APELLIDOS.length)]
      const ap2 = APELLIDOS[Math.floor(rand() * APELLIDOS.length)]
      const name = `${nombre} ${ap1} ${ap2}`

      const muni = rand() < 0.45 ? madrid : others[Math.floor(rand() * others.length)]
      const calle = CALLES[Math.floor(rand() * CALLES.length)]
      const num = 1 + Math.floor(rand() * 120)
      const cp = `28${String(1 + Math.floor(rand() * 999)).padStart(3, '0')}`
      const phone = `6${String(10_000_000 + Math.floor(rand() * 89_999_999))}`
      const ibanBody = Array.from({ length: 22 }, () => Math.floor(rand() * 10)).join('')

      people.push({
        id: `person-s${seq}`,
        name,
        email: `${slug(nombre)}.${slug(ap1)}${seq}@fbm-anotadores.example`,
        phone,
        role: 'anotador',
        category,
        address: `${calle} ${num}, ${cp} ${muni.name}`,
        postalCode: cp,
        municipalityId: muni.id,
        bankIban: `ES${ibanBody}`,
        active: true,
        hasCar: rand() < 0.85,
        authUserId: null,
        createdAt: new Date('2025-09-01'),
        nick: nickPool[REFEREE_TOTAL + n],
      })
      n++
    }
  }

  return people
}
